CREATE DATABASE bsp;

CREATE TABLE user_info (
    id SERIAL PRIMARY KEY,
    idcard TEXT,
    title TEXT,
    firstname TEXT,
    lastname TEXT,
    birthday DATE,
    tel TEXT,
    email TEXT,
    weight TEXT,
    height TEXT,
    gender TEXT,
    isCovidTest BOOLEAN,
    proofType INT,
    isDetected BOOLEAN,
    proofUrl TEXT,
    address TEXT,
    province TEXT,
    district TEXT,
    subDistrict TEXT,
    postalCode TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE symtom (
    id SERIAL PRIMARY KEY,
    fever BOOLEAN,
    cough BOOLEAN,
    snot BOOLEAN,
    sore_throat BOOLEAN,
    smell BOOLEAN,
    taste BOOLEAN,
    conjunctivitis BOOLEAN,
    rash BOOLEAN,
    liquid_stool BOOLEAN,
    liquid_stool_frequenly BOOLEAN,
    angina BOOLEAN,
    tired BOOLEAN,
    dizzy BOOLEAN,
    pneumonia BOOLEAN,
    complication BOOLEAN,
    sore_breath BOOLEAN,
    slow_response BOOLEAN,
    unconscious BOOLEAN,
    onset_date DATE,
    diabetes_obesity BOOLEAN,
    complications BOOLEAN,
    cardiovascular BOOLEAN,
    heart_failure BOOLEAN,
    lung_disease BOOLEAN,
    asthma BOOLEAN,
    chronic_lung BOOLEAN,
    malignant_tumors BOOLEAN,
    cancer BOOLEAN,
    chronic_kidney BOOLEAN,
    ckd34 BOOLEAN,
    kidney_failure_transplant BOOLEAN,
    rheumatoid_arthritis BOOLEAN,
    immunosuppressants BOOLEAN,
    chronic_liver BOOLEAN,
    respire_rate INT,
    pulse INT,
    o2_flowrate INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);